### ISSUE TITLE
dev/guion-bluford regression: allow ref's in dbt_project.yml var configs

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1047]
### Issue description
The `vars` config in a `models:` block of `dbt_project.yml` should support `ref()` functions, but they currently fail with the error: `'ref' is undefined`. I think this indicates that the compilation context for these `vars` configs has changed, though I'm not sure exactly in which branch that occurred.

In addition to the `ref` function working, we sure be sure to maintain parity with the context provided in 0.11.x, unless we explicitly choose to make breaking changes.

The error message here is pretty sparse -- it took me a while to track down the source of this issue. @beckjake - are you separately working on related code here? Something about error handling for jinja code sounds familiar, but I might be misremembering things. The actual error reads:

```
$ dbt -d run
Encountered an error:
Compilation Error
  'ref' is undefined
```

with no further info about it in the logs.

### Results
`'ref' is undefined` (see example below)

### System information
The output of `dbt --version`: dev/guion-bluford

### Steps to reproduce

```
# dbt_project.yml

models:
    vars:
        abc: '{{ ref("some_model") }}'
```

```bash
$ dbt compile
```

**Comment by beckjake** [comment]
vars + project.yml + new bug = Almost certainly caused by PR #1033
