### ISSUE TITLE
support macros in pre- and post- hooks

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#347]
Regression in `development` (this worked in 0.7.1). We should also add tests for this.

```
Encountered an error:
! Compilation error while compiling model <None>:
! post-hook for model fishtown.my_model is not a string!
```

**Comment by cmcarthur** [comment]
👍 I can look at this today

**Comment by drewbanin** [comment]
thanks @cmcarthur :+1:
