### PR TITLE
Preserve the case of schemas and databases when listing relations (#2403)

### LINKED ISSUE #2403: dbt seed not working in 0.17.0-b1
### Describe the bug
dbt seed fails to load seed files

### Steps To Reproduce
`dbt seed --full-refresh`

### Expected behavior
with 0.16 --full-refresh was not required, now it seems to be but is not working (yet?)

### Screenshots and log output
```
Completed with 7 errors and 0 warnings:

Database Error in seed data_geo_mapping_at (data\data_geo_mapping_at.csv)
  002002 (42710): SQL compilation error:
  Object 'C2061500.SCHEMA."data_geo_mapping_at"' already exists.
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0-b1
   latest version: 0.16.1

Your version of dbt is ahead of the latest release!

Plugins: [empty, but dbt-utils and snowflake-spend are installed]
```

**The operating system you're using:**
Windows 10 64bit

**The output of `python --version`:**
Python 3.8.2

### PR DESCRIPTION
**Pull request by beckjake**
resolves #2403 

### Description
There's hopefully nothing too wild or controversial in here - this is a substantial change, but it should fix some correctness issues in how dbt lists schemas. I think in the long run this will be more pleasant for adapter authors than having to figure out how to render the database/schema in each of those, and just defer it to the relations.

Change `list_relations_without_caching` (both the macro and the method) to take a single argument, a `Relation` with no `identifier` and `identifier` set to not include. Macros can use this to get a database-specific representation of the relation. The logic around creating missing schemas was updated similarly - dbt will faithfully issue "create schema" statements for whatever you give it, rather than coercing everything to lowercase and wrapping it in the given quoting.

In the process and for the same reasons, I updated `drop_schema` and `create_schema` to take the same kind of argument.

### Checklist
 - [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [X] I have run this code in development and it appears to resolve the stated issue
 - [X] This PR includes tests, or tests are not required/relevant for this PR
 - [X] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

File: core/dbt/task/runnable.py [hunk 1]
```diff
@@ -496,21 +491,23 @@ def create_schema(db: str, schema: str) -> None:
...
                 existing_schemas_lowered.update(ls_future.result())
 
-            for info, schema in required_schemas.search():
+            for info in required_schemas:
                 if info.database is None:
                     raise InternalException(
                         'Got an information schema with no database!'
                     )
+                if info.schema is None:
+                    # we are not in teh business of creating null schemas, so
```
Comment (drewbanin) [inline core/dbt/task/runnable.py:500]:
```suggestion
                    # we are not in the business of creating null schemas, so
```
:D

File: core/dbt/adapters/base/impl.py [hunk 2]
```diff
@@ -333,7 +341,14 @@ def _relations_cache_for_schemas(self, manifest: Manifest) -> None:
         # it's possible that there were no relations in some schemas. We want
         # to insert the schemas we query into the cache's `.schemas` attribute
         # so we can check it later
-        self.cache.update_schemas(schema_map.schemas_searched())
+        cache_update: Set[Tuple[str, Optional[str]]] = set()
+        for relation in cache_schemas:
+            if relation.database is None:
```
[the remark this answers is not in the document]
Comment (beckjake) [reply core/dbt/adapters/base/impl.py:346]: Spark will already need to be updated, as it overrides `_get_cache_schemas` and `list_relations_without_caching`.

I think this change will actually make it easier for spark to handle it: it sets `database = schema` but the include policy for relations is set to `database=False` - there's probably a couple rough edges to clear up, but my goal is that spark's default include policy + behavior will play pretty nicely with this and we can delete the create/drop schema implementations, at least.
